POST http://localhost:8080/books
Content-Type: application/json

{
  "title" : "Harry Potter",
  "authorIds" : [
    7
  ]
}

###
POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "J.K. Rowling",
  "bookIds": [
  ]
}

###
GET http://localhost:8080/authors


###
GET http://localhost:8080/books
